/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Events = {
  _id: string;
  _type: "events";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  date?: string;
  location?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "pub";
  };
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  hero?: {
    headline?: string;
    subhead?: string;
    backgroundImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  intro?: string;
};

export type Beer = {
  _id: string;
  _type: "beer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  description?: string;
  abv?: number;
  style?: string;
  allergens?: Array<string>;
  brewery?: string;
  comingSoon?: boolean;
  availableDate?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Staff = {
  _id: string;
  _type: "staff";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  funfact?: string;
  mugshot?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Pub = {
  _id: string;
  _type: "pub";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  tagline?: string;
  availability?: Array<{
    _key: string;
  } & AvailabilityDay>;
  address?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  beers?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "beer";
  }>;
  staff?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "staff";
  }>;
};

export type AvailabilityDuration = {
  _type: "availabilityDuration";
  from?: "12:00 AM" | "12:15 AM" | "12:30 AM" | "12:45 AM" | "1:00 AM" | "1:15 AM" | "1:30 AM" | "1:45 AM" | "2:00 AM" | "2:15 AM" | "2:30 AM" | "2:45 AM" | "3:00 AM" | "3:15 AM" | "3:30 AM" | "3:45 AM" | "4:00 AM" | "4:15 AM" | "4:30 AM" | "4:45 AM" | "5:00 AM" | "5:15 AM" | "5:30 AM" | "5:45 AM" | "6:00 AM" | "6:15 AM" | "6:30 AM" | "6:45 AM" | "7:00 AM" | "7:15 AM" | "7:30 AM" | "7:45 AM" | "8:00 AM" | "8:15 AM" | "8:30 AM" | "8:45 AM" | "9:00 AM" | "9:15 AM" | "9:30 AM" | "9:45 AM" | "10:00 AM" | "10:15 AM" | "10:30 AM" | "10:45 AM" | "11:00 AM" | "11:15 AM" | "11:30 AM" | "11:45 AM" | "12:00 PM" | "12:15 PM" | "12:30 PM" | "12:45 PM" | "1:00 PM" | "1:15 PM" | "1:30 PM" | "1:45 PM" | "2:00 PM" | "2:15 PM" | "2:30 PM" | "2:45 PM" | "3:00 PM" | "3:15 PM" | "3:30 PM" | "3:45 PM" | "4:00 PM" | "4:15 PM" | "4:30 PM" | "4:45 PM" | "5:00 PM" | "5:15 PM" | "5:30 PM" | "5:45 PM" | "6:00 PM" | "6:15 PM" | "6:30 PM" | "6:45 PM" | "7:00 PM" | "7:15 PM" | "7:30 PM" | "7:45 PM" | "8:00 PM" | "8:15 PM" | "8:30 PM" | "8:45 PM" | "9:00 PM" | "9:15 PM" | "9:30 PM" | "9:45 PM" | "10:00 PM" | "10:15 PM" | "10:30 PM" | "10:45 PM" | "11:00 PM" | "11:15 PM" | "11:30 PM" | "11:45 PM";
  to?: "12:00 AM" | "12:15 AM" | "12:30 AM" | "12:45 AM" | "1:00 AM" | "1:15 AM" | "1:30 AM" | "1:45 AM" | "2:00 AM" | "2:15 AM" | "2:30 AM" | "2:45 AM" | "3:00 AM" | "3:15 AM" | "3:30 AM" | "3:45 AM" | "4:00 AM" | "4:15 AM" | "4:30 AM" | "4:45 AM" | "5:00 AM" | "5:15 AM" | "5:30 AM" | "5:45 AM" | "6:00 AM" | "6:15 AM" | "6:30 AM" | "6:45 AM" | "7:00 AM" | "7:15 AM" | "7:30 AM" | "7:45 AM" | "8:00 AM" | "8:15 AM" | "8:30 AM" | "8:45 AM" | "9:00 AM" | "9:15 AM" | "9:30 AM" | "9:45 AM" | "10:00 AM" | "10:15 AM" | "10:30 AM" | "10:45 AM" | "11:00 AM" | "11:15 AM" | "11:30 AM" | "11:45 AM" | "12:00 PM" | "12:15 PM" | "12:30 PM" | "12:45 PM" | "1:00 PM" | "1:15 PM" | "1:30 PM" | "1:45 PM" | "2:00 PM" | "2:15 PM" | "2:30 PM" | "2:45 PM" | "3:00 PM" | "3:15 PM" | "3:30 PM" | "3:45 PM" | "4:00 PM" | "4:15 PM" | "4:30 PM" | "4:45 PM" | "5:00 PM" | "5:15 PM" | "5:30 PM" | "5:45 PM" | "6:00 PM" | "6:15 PM" | "6:30 PM" | "6:45 PM" | "7:00 PM" | "7:15 PM" | "7:30 PM" | "7:45 PM" | "8:00 PM" | "8:15 PM" | "8:30 PM" | "8:45 PM" | "9:00 PM" | "9:15 PM" | "9:30 PM" | "9:45 PM" | "10:00 PM" | "10:15 PM" | "10:30 PM" | "10:45 PM" | "11:00 PM" | "11:15 PM" | "11:30 PM" | "11:45 PM";
};

export type AvailabilityDay = {
  _type: "availabilityDay";
  day?: "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday" | "Sunday";
  availableTimes?: Array<{
    _key: string;
  } & AvailabilityDuration>;
};

export type Availability = Array<{
  _key: string;
} & AvailabilityDay>;

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = Events | Homepage | Beer | Staff | Pub | AvailabilityDuration | AvailabilityDay | Availability | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: PUBS_QUERY
// Query: *[_type == "pub" && defined(slug.current)][0...12]{  _id,   name,   slug,   image {     ...,    asset -> {       url,       metadata { dimensions }     }   }, }
export type PUBS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  image: {
    asset: {
      url: string | null;
      metadata: {
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;
// Variable: PUB_QUERY
// Query: *[_type == "pub" && slug.current == $slug][0]{  name,   tagline,   address,   image {     ...,    asset -> {       url,       metadata { dimensions }     }   },   "openingHours": availability,   beers[] -> {    name,     description  },  staff[] -> {    name,     role  }}
export type PUB_QUERYResult = {
  name: string | null;
  tagline: string | null;
  address: string | null;
  image: {
    asset: {
      url: string | null;
      metadata: {
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  openingHours: Array<{
    _key: string;
  } & AvailabilityDay> | null;
  beers: Array<{
    name: string | null;
    description: string | null;
  }> | null;
  staff: Array<{
    name: string | null;
    role: string | null;
  }> | null;
} | null;
// Variable: HOME_QUERY
// Query: *[_type == "homepage" && slug.current == "/home"]{  slug,  title,  intro,  hero {    headline,    subhead,    backgroundImage {       ...,      asset -> {         url,         metadata { dimensions }       }     }  }}
export type HOME_QUERYResult = Array<{
  slug: Slug | null;
  title: string | null;
  intro: string | null;
  hero: {
    headline: string | null;
    subhead: string | null;
    backgroundImage: {
      asset: {
        url: string | null;
        metadata: {
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
}>;
// Variable: EVENTS_QUERY
// Query: *[_type == "events" && date >= now()] | order(date asc)[0...3]{  title,  description,  date,    location -> {    name,    slug  },  image {     ...,    asset -> {       url,       metadata { dimensions }     }   }}
export type EVENTS_QUERYResult = Array<{
  title: string | null;
  description: string | null;
  date: string | null;
  location: {
    name: string | null;
    slug: Slug | null;
  } | null;
  image: {
    asset: {
      url: string | null;
      metadata: {
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"pub\" && defined(slug.current)][0...12]{\n  _id, \n  name, \n  slug, \n  image { \n    ...,\n    asset -> { \n      url, \n      metadata { dimensions } \n    } \n  }, \n}": PUBS_QUERYResult;
    "*[_type == \"pub\" && slug.current == $slug][0]{\n  name, \n  tagline, \n  address, \n  image { \n    ...,\n    asset -> { \n      url, \n      metadata { dimensions } \n    } \n  }, \n  \"openingHours\": availability, \n  beers[] -> {\n    name, \n    description\n  },\n  staff[] -> {\n    name, \n    role\n  }\n}": PUB_QUERYResult;
    "*[_type == \"homepage\" && slug.current == \"/home\"]{\n  slug,\n  title,\n  intro,\n  hero {\n    headline,\n    subhead,\n    backgroundImage { \n      ...,\n      asset -> { \n        url, \n        metadata { dimensions } \n      } \n    }\n  }\n}": HOME_QUERYResult;
    "*[_type == \"events\" && date >= now()] | order(date asc)[0...3]{\n  title,\n  description,\n  date,\n    location -> {\n    name,\n    slug\n  },\n  image { \n    ...,\n    asset -> { \n      url, \n      metadata { dimensions } \n    } \n  }\n}": EVENTS_QUERYResult;
  }
}
